#bicycle_controller:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# Position Controllers --------------------------------------
#Rev1_position_controller:
 # type: effort_controllers/JointPositionController
 # joint: Rev1
 # pid: {p: 100.0, i: 0.01, d: 10.0}
front_fork_controller:
  type: position_controllers/JointPositionController
  joint: Rev2
back_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: Rev3
